app/config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'

  get 'messages/create'

  devise_for :users, :controllers => { :registrations => "registrations" }

  root "rooms#index"

  resources :users do
    resource :room do
      resources :messages
    end
  end

end

app/app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, :presence => true

  belongs_to :user
  belongs_to :room
end

app/app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many   :messages, :dependent => :destroy
end

app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :email, :password, :password_confirmation, :presence => true

  has_one :room, :dependent => :destroy
  has_many :messages, :dependent => :destroy
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_user_and_room

  def index
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.room = @room
    @message.save
  end

  private
  def set_user_and_room
    @user = User.find(params[:user_id])
    @room = @user.room
  end

  def message_params
    params.require(:message).permit(:body)
  end
end

app/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    set_user
    @user.create_room(room_params)
    redirect_to user_room_path
  end

  def show
    set_user
    @room = @user.room
  end

  def destroy
    set_user
    @room = @user.room
    @room.destroy
    redirect_to root_path
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

  def room_params
    params.require(:room).permit(:user_id, :name, :video_url)
  end
end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/messages_helper.rb
module MessagesHelper
end

app/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/app/helpers/rooms_helper.rb
module RoomsHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/application/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Cinecast", root_path, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.username %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Your profile", user_path(current_user) %></li>
                <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Create room", new_user_room_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "application/header" %>

  <div id="wrap">
    <div class="container">
      <%= yield %>
    </div>
    <div id="push"></div>
  </div>

</body>
</html>

app/app/views/messages/_message.html.erb
<div class="row message-bubble">
  <p class="text-muted"><%= message.user.username %></p>
  <p><%= message.body %></p>
</div>

app/app/views/messages/create.js.erb
<% publish_to "/messages/new" do %>
  $("#chat").append("<%= j render @message %>");
  console.log("New message added");
<% end %>
$("#new_message")[0].reset();

app/app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/app/views/rooms/_room.html.erb
<tr>
  <td><%= link_to room.name + " (" + room.user.username + ")",
                  user_room_path(room.user.id) %></td>
  <td><%= VideoInfo.new(room.video_url).title %></td>
</tr>

app/app/views/rooms/index.html.erb
<div class="container">
  <div class="container">
    <div class="col-md-12">
      <div class="page-header">
        <h1 class="text-center">Welcome. Again.</h1>
      </div>
      <p class="lead text-center">Cinecast - a place to enjoy your Youtube videos.
        Register the room, set it to your taste, gather your friends and start watching - together.</p>
      <br/>
      <div class="table-name">Open rooms</div>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Room</th>
            <th>Playing</th>
          </tr>
        </thead>
        <%= render @rooms %>
      </table>
    </div>
  </div>
</div>

app/app/views/rooms/new.html.erb
<div class="col-lg-10 col-lg-offset-1">
  <div class="form-group">
    <%= form_for @room, url: {:action => :create} do |f| %>
      <p>
        <%= f.label "Title" %>
        <%= f.text_field :name, class: 'form-control' %>
      </p>

      <p>
        <%= f.label "Youtube URL" %>
        <%= f.text_field :video_url, class: 'form-control' %>
      </p>

      <div class="btn-group" role="group">
        <%= f.submit class: 'btn btn-success', id: "submit" %>
      </div>
    <% end %>
  </div>
</div>

app/app/views/rooms/show.html.erb
<div class="container">
  <div class="container">
    <div class="col-md-12">
      <div class="text-left">
        <h1><%= @user.username %></h1>
      </div>

      <div class="col-md-4">
        <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              Chat
            </div>
            <div class="panel-body">
              <ul id="chat">
                <%= render @room.messages.all %>
              </ul>
              <div class="panel-footer">
                  <%= form_for [@user, @room, @room.messages.build], remote: true do |f| %>
                    <div class="input-group">
                      <%= f.text_field :body, class: "form-control" %>
                      <span class="input-group-btn">
                        <%= f.submit "Send", class: "btn btn-default" %>
                      </span>
                    </div>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-8">
        <div class="component component-video embed-responsive embed-responsive-16by9">
          <%= VideoInfo.new(@room.video_url).embed_code.html_safe %>
        </div>
        <br/>
        <% if @room.user == current_user %>
          <%= button_to "Delete room", user_room_path, method: :delete,
                                                       class: "btn btn-danger",
                                                       id: "delete_btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= subscribe_to "/messages/new" %>

app/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>